webapp:
  name: #Application name
  group: #Applications name
  path: #Suffix to use for URL. Typically just / but could be things like /api/v1 
  autoscale:
    minReplicaCount: #Minimum number of replicas to run for the deployment
    maxReplicaCount: #Maximum number of replicas to run for the deployment
    cpuAverageUtilization: # Average CPU load to maintain across all replicas
  tls:
    fqdn: #FQDN
    #The TLS secretName should be unique to the FQDN as it is used to deploy a TLS certificate for that specific FQDN
    #In the example below replace #HOST with the application name for a unique incommon issued certificate
    secretName: incommon-cert-#HOST
  container: 
    image: #The container image name to use and container registry to use (Docker Hub is the default)
    port: #The container port to expose
    memory: # The amount of memory (G) to allocate for the image
    cpu: # The number of CPUs to allocate for the image
  